In [1]:
import torch

In [7]:
a = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.tensor([[7,8,9]])

In [8]:
torch.cat((a, b), axis=0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
a[0,1] = 1
a 

tensor([[1, 1, 3],
        [4, 5, 6]])

In [6]:
x = [1,2]
y = [10, 20, 30]
z = [100 , 200, 300, 400]
x = torch.tensor(x)
y = torch.tensor(y)
z = torch.tensor(z)
xyz_mesh = torch.meshgrid(x, y, z, indexing='ij')
xyz_mesh

(tensor([[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]],
 
         [[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]]),
 tensor([[[10, 10, 10, 10],
          [20, 20, 20, 20],
          [30, 30, 30, 30]],
 
         [[10, 10, 10, 10],
          [20, 20, 20, 20],
          [30, 30, 30, 30]]]),
 tensor([[[100, 200, 300, 400],
          [100, 200, 300, 400],
          [100, 200, 300, 400]],
 
         [[100, 200, 300, 400],
          [100, 200, 300, 400],
          [100, 200, 300, 400]]]))

In [7]:
params = torch.stack(xyz_mesh, dim=-1)
print(params.shape)
params

torch.Size([2, 3, 4, 3])


tensor([[[[  1,  10, 100],
          [  1,  10, 200],
          [  1,  10, 300],
          [  1,  10, 400]],

         [[  1,  20, 100],
          [  1,  20, 200],
          [  1,  20, 300],
          [  1,  20, 400]],

         [[  1,  30, 100],
          [  1,  30, 200],
          [  1,  30, 300],
          [  1,  30, 400]]],


        [[[  2,  10, 100],
          [  2,  10, 200],
          [  2,  10, 300],
          [  2,  10, 400]],

         [[  2,  20, 100],
          [  2,  20, 200],
          [  2,  20, 300],
          [  2,  20, 400]],

         [[  2,  30, 100],
          [  2,  30, 200],
          [  2,  30, 300],
          [  2,  30, 400]]]])

In [9]:
params_list = params.reshape((-1,3))
print(params_list.shape)
params_list

torch.Size([24, 3])


tensor([[  1,  10, 100],
        [  1,  10, 200],
        [  1,  10, 300],
        [  1,  10, 400],
        [  1,  20, 100],
        [  1,  20, 200],
        [  1,  20, 300],
        [  1,  20, 400],
        [  1,  30, 100],
        [  1,  30, 200],
        [  1,  30, 300],
        [  1,  30, 400],
        [  2,  10, 100],
        [  2,  10, 200],
        [  2,  10, 300],
        [  2,  10, 400],
        [  2,  20, 100],
        [  2,  20, 200],
        [  2,  20, 300],
        [  2,  20, 400],
        [  2,  30, 100],
        [  2,  30, 200],
        [  2,  30, 300],
        [  2,  30, 400]])

In [13]:
params_list.unsqueeze(-1).shape

torch.Size([24, 3, 1])